import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

// Helper to generate a random number within a range
const rand = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

// Sample realistic datasets
const incomeCategories = ['Salary', 'Freelance', 'Dividends', 'Consulting', 'Bonus', 'Investment'];
const expenseCategories = ['Groceries', 'Rent', 'Utilities', 'Entertainment', 'Transport', 'Healthcare', 'Dining', 'Software Subscriptions', 'Travel'];
const paymentMethods = ['CARD', 'CASH', 'TRANSFER', 'CRYPTO'];
const statuses = ['COMPLETED', 'PENDING', 'FAILED'];
const currencies = ['USD', 'INR', 'EUR', 'GBP'];

function generateRandomRecords(count: number, userIds: string[]) {
  const records = [];
  const now = new Date();

  for (let i = 0; i < count; i++) {
    const isIncome = Math.random() > 0.65; // ~35% chance of being income
    const type = isIncome ? 'INCOME' : 'EXPENSE';
    const amount = isIncome ? rand(100, 5000) : rand(10, 800);
    const category = isIncome 
      ? incomeCategories[rand(0, incomeCategories.length - 1)]
      : expenseCategories[rand(0, expenseCategories.length - 1)];

    // Spread dates randomly across the last 365 days
    const pastDays = rand(0, 365);
    const date = new Date(now.getTime() - pastDays * 24 * 60 * 60 * 1000);

    records.push({
      amount: amount + (rand(0, 99) / 100), // Adds decimal complexity
      type,
      category,
      date,
      paymentMethod: paymentMethods[rand(0, paymentMethods.length - 1)],
      status: statuses[rand(0, statuses.length - 1)],
      currency: currencies[rand(0, currencies.length - 1)],
      userId: userIds[rand(0, userIds.length - 1)],
      notes: `Automated ${type.toLowerCase()} record generated by seed script.`,
    });
  }

  return records;
}

async function main() {
  console.log('Start massive seeding operation...');

  // 1. Clean up existing data
  await prisma.record.deleteMany({});
  await prisma.user.deleteMany({});

  const passwordHash = await bcrypt.hash('password123', 10);

  // 2. Create foundational users
  console.log('Creating users...');
  const admin = await prisma.user.create({
    data: {
      name: 'Rahul Admin',
      email: 'rahul.admin@Finance.zorvyn.com',
      password: passwordHash,
      role: 'ADMIN',
    },
  });

  const analyst = await prisma.user.create({
    data: {
      name: 'Priya Analyst',
      email: 'priya.analyst@Finance.zorvyn.com',
      password: passwordHash,
      role: 'ANALYST',
    },
  });

  const viewer = await prisma.user.create({
    data: {
      name: 'Amit Viewer',
      email: 'amit.viewer@Finance.zorvyn.com',
      password: passwordHash,
      role: 'VIEWER',
    },
  });

  const userIds = [admin.id, analyst.id, viewer.id];
  console.log(`Users established.`);

  // 3. Generate massive dataset
  const recordCount = 1000;
  console.log(`Generating ${recordCount} random financial records tied to users...`);
  const massiveRecords = generateRandomRecords(recordCount, userIds);

  // 4. Insert chunks to avoid overwhelming the database connection
  console.log(`Pushing records to database...`);
  await prisma.record.createMany({
    data: massiveRecords,
  });

  console.log(`Successfully seeded ${recordCount} complex relational records!`);
  console.log('Seeding finished.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
